@startuml

interface Strategy {
  + algorithm(): void
}

class ConcreteStrategyA {
  + algorithm(): void
}

class ConcreteStrategyB {
  + algorithm(): void
}

class Context {
  - strategy: Strategy
  + setStrategy(strategy: Strategy): void
  + executeAlgorithm(): void
}

Context *-- Strategy : has-a

Context --> ConcreteStrategyA : uses
Context --> ConcreteStrategyB : uses

@enduml
